### ISSUE TITLE
good way to add bt owner reference in blackboard?

### ISSUE THREAD

**Issue by delmarle** [luis-l/BonsaiBehaviourTree#12]
Here is an example condition:
`namespace Bonsai.Standard
{
    [BonsaiNode("Conditional/", "Condition")]
    public class HasEnemy : ConditionalAbort
    {
        public override bool Condition()
        {
            var character = Blackboard.Get<BaseCharacter>("baseCharacter");
            return character.Target != null;
        }
    }
}`

do you have an example how to initialize that blackboard so it is correctly instanced with its owner so each unique character have their own instance of blackboard.

also if i assign the same scriptable BT to 2 different character, will they share the same scriptable BT or make instances?

**Comment by luis-l** [comment]
At Play Mode start, if there are any game objects in the scene with a Bonsai Tree Component with a valid BT Asset set, each game object will get a cloned copy of the tree asset (Tree, Nodes, and Blackboard will be a unique instance). This is done by the Bonsai Manager script for convenience in `Awake()`.

You could setup your trees manually to fit your needs.

Share same blackboard
```csharp
var bb = ScriptableObject.CreateInstance<Blackboard>();
alphaTree.SetBlackboard(bb);
betaTree.SetBlackboard(bb);
```

Behaviour Trees also have the `actor` variable which is the owning game object. `BehaviourTree.actor`. 

This value is setup by the BonsaiManager in `Awake()`. The actor variable is an optional variable for convenience. BehaviourTrees do not need a game object to run.

And I need to work on documentation :(

**Comment by delmarle** [comment]
thanks, i will check what you shared, having it cloned is really cool and i dont think i need to use blackboard for caching actor component. 
if i come with a soft caching method for actor component i will share it.
since your last push it become really stable now.
