### ISSUE TITLE
Remove the need for temporary save directory

### ISSUE THREAD

**Issue by luis-l** [luis-l/BonsaiBehaviourTree#3]
When creating a new Behaviour Tree from the editor, it creates and saves the new asset in a specified temporary directory that cannot be changed.

The directory is also useless. Temporary(unsaved) trees are immediately removed when entering play mode or closing the window.

When creating a new tree for the first time, it should not be saved any where. Saving only occurs when the user does a Save/SaveAs action.

**Comment by rgardler** [comment]
I agree the temporary folder thing should go away. But in terms of the create/save workflow I wonder if it would be better to have a more "Unity" way of doing things.

Why not create the tree as an asset from the create menu? Then double clicking opens in the editor.

Saving should be upon save or upon the editor losing reference to the asset such as opening a different tree or entering play. In most cases saving should be automatic, but I guess it could be a dialog asking to save if the tree is dirty. Especially if there is an option to always save.

It seems strange to me that there is a different workflow for creating Bonsai assets than there is for every other asset in Unity.

**Comment by luis-l** [comment]
Temporary folder nonsense has been removed.

**Comment by luis-l** [comment]
Adding Create Tree from Create Menu should be straight forward now.

**Comment by luis-l** [comment]
Tree Assets should automatically save when entering play mode already. They also automatically save when loading a new tree, creating a new tree asset, or when the window is Disabled (closed).

**Comment by luis-l** [comment]
Behaviour Tree assets can now be added from the Create Menu.
